
kind: pipeline
name: rocker/r-rmd

steps:
- name: build 'n check
  image: rocker/r-rmd
  commands:
  - R CMD build .
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - export _R_CHECK_CRAN_INCOMING_=FALSE 
  - export _R_CHECK_FORCE_SUGGESTS_=FALSE 
  - R CMD check $FILE --as-cran
