# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
                                                                                        
dist: bionic                                                                                                  

sudo: false
cache: packages

addons:
  apt:
    packages:
    - ghostscript
